POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VyMiIsImlkIjoiNjNiMjExMmZhZWU3N2MxNWE1YjVhMzZkIiwiaWF0IjoxNjcyNjg0NDY5fQ.dtS1-a_M9z8LOCMnqxMUdDFLxsGCcRgR6qvBNjExxwA

{
    "title": "testTitle",
    "author": "testAuthor",
    "url": "testUrl",
    "likes": 69
}