services:
  app:
    image: library-front-dev
    build:
      context: ./library-frontend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./library-frontend/:/usr/src/app/
    container_name: library-front-dev

  server:
    image: library-back-dev
    build:
      context: ./library-backend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./library-backend/:/usr/src/app/
    container_name: library-back-dev

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: library-reverse-proxy-dev
    depends_on:
      - app
      - server
