services:
  app:
    image: library-front
    build:
      context: ./library-frontend/
      dockerfile: Dockerfile
    container_name: library-front

  server:
    image: library-back
    build:
      context: ./library-backend/
      dockerfile: Dockerfile
    container_name: library-back

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: library-reverse-proxy
    depends_on:
      - app
      - server
